sources:
  pokeapi:
    type: api
    base_url: "https://pokeapi.co"
    endpoints:
      pokemon:
        method: "GET"
        path: "/api/v2/pokemon"
        params:
          offset: "{page}"
          limit: "100"
      pokemon_abilities:
        method: "GET"
        path: "/api/v2/pokemon/{id}/"
        params: ~
        dependencies:
          pokemon: 
            id: id

parser:
  pokeapi:
    type: api
    introspection:
          value: "results"
    pagination: 
      type: offset
      offset_size: 100
  
  
  
  # sqlserver:
  #   type: database
  #   host: "Testurl_host"

  # endpoints:
  #   - name: "pokemon"
  #     path:
  #     params:
  #     method: "GET"
      
  #   - name: ""

