sources:
  pokeapi:
    type: api
    base_url: "https://pokeapi.co"
    endpoints:
      pokemon:
        method: "GET"
        path: "/api/v2/pokemon"
        introspection:
          value: "results"
        params:
          offset: "200000"
          limit: "100"
        pagination: offset
      pokemon_abilities:
        method: "GET"
        path: "/api/v2/pokemon/{id}/"
        params: ~
        dependencies:
          pokemon: 
            id: id

parser:
  pokeapi:
    type: api
    
  
  
  
  # sqlserver:
  #   type: database
  #   host: "Testurl_host"

  # endpoints:
  #   - name: "pokemon"
  #     path:
  #     params:
  #     method: "GET"
      
  #   - name: ""

